// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://houvfgnwbytnwzwvenbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdXZmZ253Ynl0bnd6d3ZlbmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODQwNTksImV4cCI6MjA1Mjk2MDA1OX0.tKmg34qWdEd6XGoCGSUxeDd9EX6wx0pY7aVVtEtER54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);